import csv
import io
import json
from typing import Dict, Any, List


class ReportExporter:
    """
    Generates structured export deliverables for ResearchOS:
    - Markdown Document
    - Printable PDF / HTML
    - Presentation / PPT Slide Deck (with transitions & speaker notes)
    - Excel / CSV Evidence Ledger
    """

    @classmethod
    def to_markdown(cls, question: str, summary: str, citations: List[Dict[str, Any]], findings: List[str] = None, gaps: List[str] = None) -> str:
        md = []
        md.append(f"# Deep Research Brief: {question}\n")
        md.append(f"**Generated by ResearchOS Multi-AI Engine**\n\n---\n")
        md.append("## Executive Summary\n")
        md.append(f"{summary}\n\n")

        if findings:
            md.append("## Key Verified Findings\n")
            for f in findings:
                md.append(f"- {f}\n")
            md.append("\n")

        if gaps:
            md.append("## Candidate Research Gaps & Future Directions\n")
            for g in gaps:
                md.append(f"- **[Candidate Gap]** {g}\n")
            md.append("\n")

        if citations:
            md.append("## Traceable Citations & Evidence Sources\n")
            for c in citations:
                tag = c.get("citation_key", "[1]")
                title = c.get("title", "Untitled Source")
                url = c.get("url", "")
                stype = c.get("type", "academic")
                md.append(f"{tag} **{title}** ({stype.upper()})  \n  URL: [{url}]({url})\n")

        return "\n".join(md)

    @classmethod
    def to_csv_evidence_ledger(cls, question: str, citations: List[Dict[str, Any]], findings: List[str] = None) -> str:
        output = io.StringIO()
        writer = csv.writer(output)
        writer.writerow(["Citation Tag", "Source Title", "Source URL", "Domain / Type", "Status"])

        for c in (citations or []):
            writer.writerow([
                c.get("citation_key", "[1]"),
                c.get("title", ""),
                c.get("url", ""),
                c.get("type", "web"),
                "Verified"
            ])
        return output.getvalue()

    @classmethod
    def to_presentation_deck(cls, question: str, summary: str, findings: List[str] = None, gaps: List[str] = None) -> Dict[str, Any]:
        """Generates structured presentation slides with speaker notes and transition cues."""
        slides = [
            {
                "slide_number": 1,
                "title": f"Research Synthesis: {question[:50]}...",
                "subtitle": "Prepared by ResearchOS Autonomous Multi-AI Engine",
                "layout": "title_slide",
                "transition": "fade",
                "bullets": ["Automated Multi-Source Extraction", "Evidentiary Verification & Gap Mapping"],
                "speaker_notes": "Welcome everyone. Today we are reviewing the synthesis of our deep research inquiry."
            },
            {
                "slide_number": 2,
                "title": "Executive Summary & Core Findings",
                "layout": "content_slide",
                "transition": "slide_left",
                "bullets": [summary[:220] + "..."],
                "speaker_notes": "The primary conclusion demonstrates key advancements with empirical backing across multiple literature sources."
            }
        ]

        if findings:
            slides.append({
                "slide_number": 3,
                "title": "Key Verified Empirical Evidence",
                "layout": "bullet_grid",
                "transition": "slide_left",
                "bullets": findings[:4],
                "speaker_notes": "These findings are directly corroborated by underlying document citations."
            })

        if gaps:
            slides.append({
                "slide_number": len(slides) + 1,
                "title": "Candidate Research Gaps & Next Steps",
                "layout": "action_slide",
                "transition": "zoom",
                "bullets": gaps[:3],
                "speaker_notes": "We highlight these underexplored directions for future engineering and scientific investigation."
            })

        return {
            "presentation_title": f"ResearchOS Deck: {question}",
            "slides_count": len(slides),
            "slides": slides
        }

    @classmethod
    def to_printable_html(cls, question: str, summary: str, citations: List[Dict[str, Any]], findings: List[str] = None) -> str:
        """Generates a clean HTML page designed for instant browser PDF printing."""
        findings_html = "".join([f"<li>{f}</li>" for f in (findings or [])])
        citations_html = "".join([
            f"<tr><td><strong>{c.get('citation_key')}</strong></td><td>{c.get('title')}</td><td><a href='{c.get('url')}' target='_blank'>{c.get('url')}</a></td><td>{c.get('type')}</td></tr>"
            for c in (citations or [])
        ])

        return f"""<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>ResearchOS Report - {question}</title>
    <style>
        body {{ font-family: 'Helvetica Neue', Arial, sans-serif; padding: 40px; color: #1e293b; line-height: 1.6; max-width: 800px; margin: 0 auto; }}
        h1 {{ color: #0f172a; border-bottom: 2px solid #6366f1; padding-bottom: 10px; font-size: 24px; }}
        h2 {{ color: #334155; margin-top: 24px; font-size: 18px; }}
        .badge {{ background: #e0e7ff; color: #4338ca; padding: 3px 8px; border-radius: 4px; font-size: 12px; font-weight: bold; }}
        .summary-box {{ background: #f8fafc; border-left: 4px solid #6366f1; padding: 16px; margin: 16px 0; border-radius: 4px; }}
        table {{ width: 100%; border-collapse: collapse; margin-top: 14px; font-size: 13px; }}
        th, td {{ border: 1px solid #e2e8f0; padding: 8px 12px; text-align: left; }}
        th {{ background: #f1f5f9; }}
        @media print {{
            body {{ padding: 0; }}
            .no-print {{ display: none; }}
        }}
    </style>
</head>
<body>
    <div class="no-print" style="margin-bottom: 20px; display: flex; justify-content: flex-end;">
        <button onclick="window.print()" style="background: #6366f1; color: white; border: none; padding: 8px 16px; border-radius: 6px; cursor: pointer; font-weight: bold;">
            Print / Save as PDF
        </button>
    </div>
    <h1>{question}</h1>
    <div><span class="badge">ResearchOS Multi-AI Brief</span></div>
    <div class="summary-box">
        <h3>Executive Summary</h3>
        <p>{summary}</p>
    </div>
    <h2>Key Verified Findings</h2>
    <ul>{findings_html}</ul>
    <h2>Traceable Evidence Sources & Citations</h2>
    <table>
        <thead>
            <tr><th>Tag</th><th>Source Title</th><th>Link</th><th>Type</th></tr>
        </thead>
        <tbody>
            {citations_html}
        </tbody>
    </table>
</body>
</html>"""
